version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.11"

# Python requirements
python:
    install:
        - requirements: docs/requirements.txt

# MkDocs settings
mkdocs:
    configuration: mkdocs.yml
    fail_on_warning: false

# Build formats
formats:
    - htmlzip
    - pdf
